// Base de datos de PELÍCULAS para Cinemax
const baseDeDatos = [
    { 
        id: "P1", 
        titulo: "El abismo secreto", 
        poster: "https://www.themoviedb.org/t/p/w600_and_h900_face/cZJaa2ZOp3wiXXw0mqqtp3d326j.jpg", 
        bg: "https://image.tmdb.org/t/p/original/uBfAZuAsEmIQ66N2OTZ8ytLEV6.jpg", 
        video: "https://www.burstcloud.co/embed/b747167e31d4ccd34d5c5fadd32d1c9f737ef12869685343a96c9ccee9974492/her%20ella.mp4", 
        descripcion: "Dos agentes altamente entrenados se unen a la distancia...", 
        fecha: "2025", 
        tags: "Romance, Ciencia ficción",
        etiqueta: "",
        coincidencia: "98% para ti",
        calidad: "HD"
    },
    { 
        id: "P2", 
        titulo: "Compañera perfecta", 
        poster: "https://www.themoviedb.org/t/p/w600_and_h900_face/m68uoULpxeDkmCetbhftXCgP1TZ.jpg", 
        bg: "https://image.tmdb.org/t/p/original/9p2tVEEWw1M92Pt63Vbq7EjBpvk.jpg", 
        video: "https://www.burstcloud.co/embed/1b72b0a9273e43f0f1f304d59d91943232442da6504940459eed6c0c5b0bc553/Companera%20perfecta.mp4", 
        descripcion: "La muerte de un multimillonario desencadena una cadena de acontecimientos para Iris y sus amigos durante un viaje de fin de semana a su propiedad junto al lago.", 
        fecha: "2025", 
        tags: "Terror, Ciencia ficción y Suspense",
        etiqueta: "",
        coincidencia: "80% para ti",
        calidad: "HD"
    },
	{ 
        id: "P3", 
        titulo: "Napoleón", 
        poster: "https://www.themoviedb.org/t/p/w600_and_h900_face/ytFOXyghxLzAM4KZyazDdEkM66q.jpg", 
        bg: "https://image.tmdb.org/t/p/original/33pMXav77ICRnceEBLhL8lXTywv.jpg", 
        video: "https://www.burstcloud.co/embed/ff55dabfd9262fee808e2f57f99ab58a2b7c83463444f88f9046df9ee5cf17b0/NAPOLEON.mp4", 
        descripcion: "Una mirada personal a los orígenes del líder militar francés y su rápido y despiadado ascenso a emperador.", 
        fecha: "2023", 
        tags: "Historia, Bélica y Romance",
        etiqueta: "",
        coincidencia: "63% para ti",
        calidad: "HD"
    },
	{ 
        id: "P4", 
        titulo: "Corazón Valiente", 
        poster: "https://www.themoviedb.org/t/p/w600_and_h900_face/6snCuOuKwWnATAOTTumAtRImuoo.jpg", 
        bg: "https://image.tmdb.org/t/p/original/8lBcqakI3F19NWkXdqE0M8W76b9.jpg", 
        video: "https://www.burstcloud.co/embed/5f9605a235e4a811d417790a769810725f0ce7dac06bdd27251fa0470f7dcacb/corazonvaliente.mp4", 
        descripcion: "Drama histórico que narra la vida de William Wallace, un héroe escocés del siglo XIII que lidera una rebelión contra el dominio inglés", 
        fecha: "1995 ", 
        tags: "Acción, Drama, Historia y Bélica",
        etiqueta: "",
        coincidencia: "79% para ti",
        calidad: "HD"
    },
	{ 
        id: "P5", 
        titulo: "Maze Runner: Correr o morir", 
        poster: "https://www.themoviedb.org/t/p/w600_and_h900_face/ode14q7WtDugFDp78fo9lCsmay9.jpg", 
        bg: "https://image.tmdb.org/t/p/original/l5ILIrAcBzja7nkKduTcKUoAAvP.jpg", 
        video: "https://www.burstcloud.co/embed/1e908ed1f88d74b9621f09a4f195c226c35ce6a02448ba22faa311d5efcc686b/Mazerunner%201.mp4", 
        descripcion: "Thomas se despierta en un ascensor sin recuerdos, solo su nombre. Al salir, encuentra un mundo extraño con jóvenes amnésicos, donde comienza una aventura que revela complejas realidades.", 
        fecha: "2014", 
        tags: "Acción, Misterio,ficción y Suspense",
        etiqueta: "",
        coincidencia: "72% para ti",
        calidad: "HD"
    },
	{ 
        id: "P6", 
        titulo: "Maze Runner: Prueba de fuego", 
        poster: "https://www.themoviedb.org/t/p/w600_and_h900_face/womQQ2ltHhYeP35kitlwzAhtUt9.jpg", 
        bg: "https://image.tmdb.org/t/p/original/ae05UlOV00BPWba2QZnRBGkuW1J.jpg", 
        video: "https://www.burstcloud.co/embed/c0342a4e86aef317371ffdf43a33bee34751f6737090595383135c522f7e5748/Mazerunner%202.mp4", 
        descripcion: "Thomas y sus compañeros deben cruzar un agreste desierto para encontrar pistas que les ayuden a combatir a la malévola organización CRUEL.", 
        fecha: "2015", 
        tags: "Acción, Misterio,ficción y Suspense",
        etiqueta: "",
        coincidencia: "67% para ti",
        calidad: "HD"
    },
	{ 
        id: "P7", 
        titulo: "Maze Runner: La cura mortal", 
        poster: "https://www.themoviedb.org/t/p/w600_and_h900_face/kuZOnvzplxPVh71t827F19zY5Ab.jpg", 
        bg: "https://image.tmdb.org/t/p/original/42wGIEoRH8DxsKO5rbtqe5WYMeX.jpg", 
        video: "https://www.burstcloud.co/embed/c0342a4e86aef317371ffdf43a33bee34751f6737090595383135c522f7e5748/Mazerunner%202.mp4", 
        descripcion: "El joven héroe Thomas no puede confiar en la organización CRUEL, entonces con sus amigos se embarca en una misión para encontrar una cura para la enfermedad mortal conocida como La Llamarada.", 
        fecha: "2018 ", 
        tags: "Acción, Misterio,ficción y Suspense",
        etiqueta: "",
        coincidencia: "74% para ti",
        calidad: "HD"
    },
	{ 
        id: "P8", 
        titulo: "Bad boys", 
        poster: "https://www.themoviedb.org/t/p/w600_and_h900_face/ZYpSdXaTMFYCGbmVmXOFbdJmSv.jpg", 
        bg: "https://image.tmdb.org/t/p/original/wQW7d19J87u1Ktt8AGqFXd5H8E.jpg", 
        video: "https://www.burstcloud.co/embed/1a1e06650cacc8cc6eca3cc1f8d658189d94a381da00623a7774769289c1d607/badboys1.mp4", 
        descripcion: "Un lote de heroína de 100 millones es robado; los agentes Burnett y Lowery deben proteger a la testigo clave.", 
        fecha: "1995", 
        tags: "Acción, Comedia, Crimen y Suspense",
        etiqueta: "",
        coincidencia: "68% para ti",
        calidad: "HD"
    },
	{ 
        id: "P9", 
        titulo: "Bad Boys II: vuelven más rebeldes", 
        poster: "https://www.themoviedb.org/t/p/w600_and_h900_face/r6qSm5p1lRaEbNOioNzhF5A4RaN.jpg", 
        bg: "https://image.tmdb.org/t/p/original/gxSVZCUlDd8upT1G2wdrUdz2hxG.jpg", 
        video: "https://www.burstcloud.co/embed/672ce7c52d22822eca2e8b75e6cdf2a78c50bf794a3108bcdec0a4d460f68e97/badboys2.mp4", 
        descripcion: "Los detectives de narcóticos Mike Lowrey y Marcus Burnett han sido asignados a un nuevo caso en Miami, donde un astuto narcotraficante ha iniciado una sangrienta guerra.", 
        fecha: "2003", 
        tags: "Acción, Comedia, Crimen y Suspense",
        etiqueta: "",
        coincidencia: "67% para ti",
        calidad: "HD"
    },
	{ 
        id: "P10", 
        titulo: "Bad Boys para Siempre", 
        poster: "https://www.themoviedb.org/t/p/w600_and_h900_face/5XR7Pbo8qdwdpOIsFtWJOEiOJD6.jpg", 
        bg: "https://image.tmdb.org/t/p/original/3EXcgNW3SyGveCSDLC38oESQ8K1.jpg", 
        video: "https://www.burstcloud.co/embed/7c816961154786ebe942f415b7a7155f126d7d88dfba8352433adada08709d35/badboys3.mp4", 
        descripcion: "La tercera parte de Dos policías rebeldes reúne a Will Smith y Martin Lawrence enfrentando un nuevo criminal.", 
        fecha: "2020", 
        tags: "Acción, Comedia, Crimen y Suspense",
        etiqueta: "",
        coincidencia: "72% para ti",
        calidad: "HD"
    },
	{ 
        id: "P11", 
        titulo: "Bad Boys: Hasta la muerte", 
        poster: "https://www.themoviedb.org/t/p/w600_and_h900_face/5jI2vEHJReAx8iFDmhC2O3yW37w.jpg", 
        bg: "https://image.tmdb.org/t/p/original/gRApXuxWmO2forYTuTmcz5RaNUV.jpg", 
        video: "https://www.burstcloud.co/embed/72360801a9e846a4c1f773c7514d5f34694ed767d19b12897690e62949fe4f0b/badboys4.mp4", 
        descripcion: "Tras escuchar falsas acusaciones sobre su excapitán y mentor Mike y Marcus deciden investigar el asunto incluso volverse los más buscados de ser necesarios.", 
        fecha: "2024", 
        tags: "Acción, Comedia, Crimen y Suspense",
        etiqueta: "",
        coincidencia: "75% para ti",
        calidad: "HD"
    },
	{ 
        id: "P12", 
        titulo: "Gladiador", 
        poster: "https://www.themoviedb.org/t/p/w600_and_h900_face/p08mUnCktZ2opGihZTAn7OqzOoi.jpg", 
        bg: "https://image.tmdb.org/t/p/original/aZtwH3RQ0L8jbInxr7OSc9tlGMJ.jpg", 
        video: "https://www.burstcloud.co/embed/fb1e061ea09e62129c3b2b2af870731307df6803ec900c09ffeacb7d1038e6ac/gladiador1.mp4", 
        descripcion: "En el año 180, Marco Aurelio transfiere el poder a Máximo, pero su hijo Cómodo intenta asesinarlo.", 
        fecha: "2021", 
        tags: "Acción, Drama y Aventura",
        etiqueta: "",
        coincidencia: "82% para ti",
        calidad: "HD"
    },
	{ 
        id: "P13", 
        titulo: "Gladiador II", 
        poster: "https://www.themoviedb.org/t/p/w600_and_h900_face/fbcs5AxrdXwyj1b8bGGMgC9kXrM.jpg", 
        bg: "https://image.tmdb.org/t/p/original/qoZHK7EVaO70jaucJYEvI1tGqRh.jpg", 
        video: "https://www.burstcloud.co/embed/1ad069bc269eff33fcadf37e90cf75c53de4b1cc2bb90a4cc1a2c29c51d46a28/gladiador2.mp4", 
        descripcion: "Lucius, tras la muerte de Maximus y la caída de su hogar, debe luchar en el Coliseo para restaurar la gloria de Roma.", 
        fecha: "2024", 
        tags: "Acción, Drama y Aventura",
        etiqueta: "",
        coincidencia: "66% para ti",
        calidad: "HD"
    },
	{ 
        id: "P14", 
        titulo: "Duna ", 
        poster: "https://www.themoviedb.org/t/p/w600_and_h900_face/gDzOcq0pfeCeqMBwKIJlSmQpjkZ.jpg", 
        bg: "https://image.tmdb.org/t/p/original/h3HsfV8Kn9Sz2QWUYYdP5ya23hx.jpg", 
        video: "https://www.burstcloud.co/embed/2989e8a490b4c2735d692de5c3d125f9a0a3c90c381d256a5a220e674221de01/Dune1.mp4", 
        descripcion: "Paul Atreides, un joven brillante y talentoso nacido en un gran destino más allá de su entendimiento, debe viajar al planeta más peligroso del universo para asegurar el futuro de su familia y de su pueblo.", 
        fecha: "2021", 
        tags: "Ciencia ficción y Aventura",
        etiqueta: "",
        coincidencia: "78% para ti",
        calidad: "HD"
    },
	{ 
        id: "P15", 
        titulo: "Duna: Parte dos", 
        poster: "https://www.themoviedb.org/t/p/w600_and_h900_face/6o5cJjA4srfvU52UKWaqPUuPPgl.jpg", 
        bg: "https://image.tmdb.org/t/p/original/wauiyiVXpdvTvt2CzdSWbYlbaE3.jpg", 
        video: "https://www.burstcloud.co/embed/a8bf356a133f0790cd576eb8c8c7daa109966b9dd597af3b9709dcf812756808/dune2.mp4", 
        descripcion: "Paul Atreides se une a Chani y los Fremen en busca de venganza contra quienes destruyeron a su familia, enfrentando una decisión entre amor y destino universal.", 
        fecha: "2024", 
        tags: "Ciencia ficción y Aventura",
        etiqueta: "",
        coincidencia: "81% para ti",
        calidad: "HD"
    },
	{ 
        id: "P16", 
        titulo: "¿Qué Pasó Ayer?", 
        poster: "https://www.themoviedb.org/t/p/w600_and_h900_face/kZaaJQEi7n3mrBct1H3l2g45Ijb.jpg", 
        bg: "https://image.tmdb.org/t/p/original/iuRVt8tFiXDPGgzavhuSa3QHRxD.jpg", 
        video: "https://www.burstcloud.co/embed/b45a563c34b55e77bb156149dceceaf1f3e3ec360a2ad8cd74388e83e3cb3fb7/quepasoayer1.mp4", 
        descripcion: "El novio y tres amigos celebran una despedida de soltero en Las Vegas. Al despertar con resaca, descubren que el novio ha desaparecido, y hay un tigre y un bebé.", 
        fecha: "2009", 
        tags: "Comedia y Aventura",
        etiqueta: "",
        coincidencia: "73% para ti",
        calidad: "HD"
    },
	{ 
        id: "P17", 
        titulo: "¿Qué Pasó Ayer? Parte II", 
        poster: "https://www.themoviedb.org/t/p/w600_and_h900_face/dzaVnS19yDTkkGZRlf89sND75i7.jpg", 
        bg: "https://image.tmdb.org/t/p/original/kdKHiiUvGpcOjxPfyblxTuGHw8o.jpg", 
        video: "https://www.burstcloud.co/embed/0f1a58989c199817466106492373059e3bc164a83419af0aa4aeb872a8f88f89/quepasoayer2.mp4", 
        descripcion: "Alan, Stu y Phil despiertan en un hotel en Tailandia sin recordar nada, y deben encontrar a Teddy, el hermano de Lauren, antes de la boda de Stu.", 
        fecha: "2011", 
        tags: "Comedia y Aventura",
        etiqueta: "ESTRENO",
        coincidencia: "69% para ti",
        calidad: "HD"
    },
	{ 
        id: "P18", 
        titulo: "¿Qué Pasó Ayer? Parte III", 
        poster: "https://www.themoviedb.org/t/p/w600_and_h900_face/1goOfrB3ZRnoJenHHIDqiskMi9q.jpg", 
        bg: "https://image.tmdb.org/t/p/original/ll7iTzMsGsPK7tfPCoiD315sHmN.jpg", 
        video: "https://www.burstcloud.co/embed/15983ba8928f6cbcdc72e1be297d4d9284397ac52dbdb7037dbb9085935b59ac/quepasoayer3.mp4", 
        descripcion: "Alan, tras la muerte de su padre, es llevado al centro por Phil, Stu y Doug, sin boda ni fiesta, solo caos con Chow.", 
        fecha: "2013", 
        tags: "Comedia y Aventura",
        etiqueta: "ESTRENO",
        coincidencia: "71% para ti",
        calidad: "HD"
    },
	{ 
        id: "P19", 
        titulo: "Deadpool", 
        poster: "https://www.themoviedb.org/t/p/w600_and_h900_face/3E53WEZJqP6aM84D8CckXx4pIHw.jpg", 
        bg: "https://image.tmdb.org/t/p/original/k2VX0gFu2BEJhvduQTq2ioYp8z7.jpg", 
        video: "https://www.burstcloud.co/embed/73a7309cc9edd69f7b740355bbd81c7aabb9545e8145aa6461031677e3ceb884/Deappool1.mp4", 
        descripcion: "Deadpool narra el origen de Wade Wilson, un ex-operativo que, tras un experimento cruel, obtiene poderes de curación y se convierte en mercenario, buscando venganza con humor retorcido.", 
        fecha: "2016", 
        tags: "Acción, Aventura y Comedia",
        etiqueta: "ESTRENO",
        coincidencia: "73% para ti",
        calidad: "HD"
    },
	{ 
        id: "P20", 
        titulo: "Deadpool 2", 
        poster: "https://www.themoviedb.org/t/p/w600_and_h900_face/fgPTa4IS07Pygz0Q1WJnRgOP7r7.jpg", 
        bg: "https://image.tmdb.org/t/p/original/ngoXNWBeJABz6i1SyNDj0d3GD6P.jpg", 
        video: "https://www.burstcloud.co/embed/7c4616920f3c49ae1fb7aecd8576ca97da21b899556ee21234beb30651973cce/deadpool2.mp4", 
        descripcion: "El mercenario mutante malhablado Wade Wilson (alias Deadpool), reúne a un equipo de mutantes para proteger a un joven con habilidades sobrenaturales del brutal cyborg Cable, que viaja a través del tiempo.", 
        fecha: "2018", 
        tags: "Acción, Aventura y Comedia",
        etiqueta: "ESTRENO",
        coincidencia: "75% para ti",
        calidad: "HD"
    },
	{ 
        id: "P21", 
        titulo: "Deadpool & Wolverine", 
        poster: "https://www.themoviedb.org/t/p/w600_and_h900_face/6aY3OzCIdxoBMYdiH5s17rWFFFA.jpg", 
        bg: "https://image.tmdb.org/t/p/original/rLLA3CehQydC9RsSwIaA54gXNPp.jpg", 
        video: "https://www.burstcloud.co/embed/2ddcb5bd4f1b280c50ece46f466d0bb5fef2d0dae2082c74c0a1f9b21ff7c9d2/deadpoolvswolverine.mp4", 
        descripcion: "Wade Wilson, apático en la vida civil, regresa como Deadpool para enfrentar una amenaza, junto al reacio Wolverine.", 
        fecha: "2024", 
        tags: "Acción, Aventura y Comedia",
        etiqueta: "ESTRENO",
        coincidencia: "76% para ti",
        calidad: "HD"
    },
];