// Base de datos de PELÍCULAS para Cinemax
const baseDeDatos = [
    { 
        id: "P1", 
        titulo: "El abismo secreto", 
        poster: "https://www.themoviedb.org/t/p/w600_and_h900_face/cZJaa2ZOp3wiXXw0mqqtp3d326j.jpg", 
        bg: "https://image.tmdb.org/t/p/original/uBfAZuAsEmIQ66N2OTZ8ytLEV6.jpg", 
        video: "https://www.burstcloud.co/embed/b747167e31d4ccd34d5c5fadd32d1c9f737ef12869685343a96c9ccee9974492/her%20ella.mp4", 
        descripcion: "Dos agentes altamente entrenados se unen a la distancia...", 
        fecha: "2025", 
        tags: "Romance, Ciencia ficción",
        etiqueta: "",
        coincidencia: "98% para ti",
        calidad: "HD"
    },
    { 
        id: "P2", 
        titulo: "Compañera perfecta", 
        poster: "https://www.themoviedb.org/t/p/w600_and_h900_face/m68uoULpxeDkmCetbhftXCgP1TZ.jpg", 
        bg: "https://image.tmdb.org/t/p/original/9p2tVEEWw1M92Pt63Vbq7EjBpvk.jpg", 
        video: "https://www.burstcloud.co/embed/1b72b0a9273e43f0f1f304d59d91943232442da6504940459eed6c0c5b0bc553/Companera%20perfecta.mp4", 
        descripcion: "La muerte de un multimillonario desencadena una cadena de acontecimientos para Iris y sus amigos durante un viaje de fin de semana a su propiedad junto al lago.", 
        fecha: "2025", 
        tags: "Terror, Ciencia ficción y Suspense",
        etiqueta: "",
        coincidencia: "80% para ti",
        calidad: "HD"
    },
	{ 
        id: "P3", 
        titulo: "Napoleón", 
        poster: "https://www.themoviedb.org/t/p/w600_and_h900_face/ytFOXyghxLzAM4KZyazDdEkM66q.jpg", 
        bg: "https://image.tmdb.org/t/p/original/33pMXav77ICRnceEBLhL8lXTywv.jpg", 
        video: "https://www.burstcloud.co/embed/ff55dabfd9262fee808e2f57f99ab58a2b7c83463444f88f9046df9ee5cf17b0/NAPOLEON.mp4", 
        descripcion: "Una mirada personal a los orígenes del líder militar francés y su rápido y despiadado ascenso a emperador.", 
        fecha: "2023", 
        tags: "Historia, Bélica y Romance",
        etiqueta: "",
        coincidencia: "63% para ti",
        calidad: "HD"
    },
	{ 
        id: "P4", 
        titulo: "Corazón Valiente", 
        poster: "https://www.themoviedb.org/t/p/w600_and_h900_face/6snCuOuKwWnATAOTTumAtRImuoo.jpg", 
        bg: "https://image.tmdb.org/t/p/original/8lBcqakI3F19NWkXdqE0M8W76b9.jpg", 
        video: "https://www.burstcloud.co/embed/5f9605a235e4a811d417790a769810725f0ce7dac06bdd27251fa0470f7dcacb/corazonvaliente.mp4", 
        descripcion: "Drama histórico que narra la vida de William Wallace, un héroe escocés del siglo XIII que lidera una rebelión contra el dominio inglés", 
        fecha: "1995 ", 
        tags: "Acción, Drama, Historia y Bélica",
        etiqueta: "",
        coincidencia: "79% para ti",
        calidad: "HD"
    },
	{ 
        id: "P5", 
        titulo: "Maze Runner: Correr o morir", 
        poster: "https://www.themoviedb.org/t/p/w600_and_h900_face/ode14q7WtDugFDp78fo9lCsmay9.jpg", 
        bg: "https://image.tmdb.org/t/p/original/l5ILIrAcBzja7nkKduTcKUoAAvP.jpg", 
        video: "https://www.burstcloud.co/embed/1e908ed1f88d74b9621f09a4f195c226c35ce6a02448ba22faa311d5efcc686b/Mazerunner%201.mp4", 
        descripcion: "Thomas se despierta en un ascensor sin recuerdos, solo su nombre. Al salir, encuentra un mundo extraño con jóvenes amnésicos, donde comienza una aventura que revela complejas realidades.", 
        fecha: "2014", 
        tags: "Acción, Misterio,ficción y Suspense",
        etiqueta: "",
        coincidencia: "72% para ti",
        calidad: "HD"
    },
	{ 
        id: "P6", 
        titulo: "Maze Runner: Prueba de fuego", 
        poster: "https://www.themoviedb.org/t/p/w600_and_h900_face/womQQ2ltHhYeP35kitlwzAhtUt9.jpg", 
        bg: "https://image.tmdb.org/t/p/original/ae05UlOV00BPWba2QZnRBGkuW1J.jpg", 
        video: "https://www.burstcloud.co/embed/c0342a4e86aef317371ffdf43a33bee34751f6737090595383135c522f7e5748/Mazerunner%202.mp4", 
        descripcion: "Thomas y sus compañeros deben cruzar un agreste desierto para encontrar pistas que les ayuden a combatir a la malévola organización CRUEL.", 
        fecha: "2015", 
        tags: "Acción, Misterio,ficción y Suspense",
        etiqueta: "",
        coincidencia: "67% para ti",
        calidad: "HD"
    },
	{ 
        id: "P7", 
        titulo: "Maze Runner: La cura mortal", 
        poster: "https://www.themoviedb.org/t/p/w600_and_h900_face/kuZOnvzplxPVh71t827F19zY5Ab.jpg", 
        bg: "https://image.tmdb.org/t/p/original/42wGIEoRH8DxsKO5rbtqe5WYMeX.jpg", 
        video: "https://www.burstcloud.co/embed/c0342a4e86aef317371ffdf43a33bee34751f6737090595383135c522f7e5748/Mazerunner%202.mp4", 
        descripcion: "El joven héroe Thomas no puede confiar en la organización CRUEL, entonces con sus amigos se embarca en una misión para encontrar una cura para la enfermedad mortal conocida como La Llamarada.", 
        fecha: "2018 ", 
        tags: "Acción, Misterio,ficción y Suspense",
        etiqueta: "",
        coincidencia: "74% para ti",
        calidad: "HD"
    },
	{ 
        id: "P8", 
        titulo: "Bad boys", 
        poster: "https://www.themoviedb.org/t/p/w600_and_h900_face/ZYpSdXaTMFYCGbmVmXOFbdJmSv.jpg", 
        bg: "https://image.tmdb.org/t/p/original/wQW7d19J87u1Ktt8AGqFXd5H8E.jpg", 
        video: "https://www.burstcloud.co/embed/1a1e06650cacc8cc6eca3cc1f8d658189d94a381da00623a7774769289c1d607/badboys1.mp4", 
        descripcion: "Un lote de heroína de 100 millones es robado; los agentes Burnett y Lowery deben proteger a la testigo clave.", 
        fecha: "1995", 
        tags: "Acción, Comedia, Crimen y Suspense",
        etiqueta: "",
        coincidencia: "68% para ti",
        calidad: "HD"
    },
	{ 
        id: "P9", 
        titulo: "Bad Boys II: vuelven más rebeldes", 
        poster: "https://www.themoviedb.org/t/p/w600_and_h900_face/r6qSm5p1lRaEbNOioNzhF5A4RaN.jpg", 
        bg: "https://image.tmdb.org/t/p/original/gxSVZCUlDd8upT1G2wdrUdz2hxG.jpg", 
        video: "https://www.burstcloud.co/embed/672ce7c52d22822eca2e8b75e6cdf2a78c50bf794a3108bcdec0a4d460f68e97/badboys2.mp4", 
        descripcion: "Los detectives de narcóticos Mike Lowrey y Marcus Burnett han sido asignados a un nuevo caso en Miami, donde un astuto narcotraficante ha iniciado una sangrienta guerra.", 
        fecha: "2003", 
        tags: "Acción, Comedia, Crimen y Suspense",
        etiqueta: "",
        coincidencia: "67% para ti",
        calidad: "HD"
    },
	{ 
        id: "P10", 
        titulo: "Bad Boys para Siempre", 
        poster: "https://www.themoviedb.org/t/p/w600_and_h900_face/5XR7Pbo8qdwdpOIsFtWJOEiOJD6.jpg", 
        bg: "https://image.tmdb.org/t/p/original/3EXcgNW3SyGveCSDLC38oESQ8K1.jpg", 
        video: "https://www.burstcloud.co/embed/7c816961154786ebe942f415b7a7155f126d7d88dfba8352433adada08709d35/badboys3.mp4", 
        descripcion: "La tercera parte de Dos policías rebeldes reúne a Will Smith y Martin Lawrence enfrentando un nuevo criminal.", 
        fecha: "2020", 
        tags: "Acción, Comedia, Crimen y Suspense",
        etiqueta: "",
        coincidencia: "72% para ti",
        calidad: "HD"
    },
	{ 
        id: "P11", 
        titulo: "Bad Boys: Hasta la muerte", 
        poster: "https://www.themoviedb.org/t/p/w600_and_h900_face/5jI2vEHJReAx8iFDmhC2O3yW37w.jpg", 
        bg: "https://image.tmdb.org/t/p/original/gRApXuxWmO2forYTuTmcz5RaNUV.jpg", 
        video: "https://www.burstcloud.co/embed/72360801a9e846a4c1f773c7514d5f34694ed767d19b12897690e62949fe4f0b/badboys4.mp4", 
        descripcion: "Tras escuchar falsas acusaciones sobre su excapitán y mentor Mike y Marcus deciden investigar el asunto incluso volverse los más buscados de ser necesarios.", 
        fecha: "2024", 
        tags: "Acción, Comedia, Crimen y Suspense",
        etiqueta: "",
        coincidencia: "75% para ti",
        calidad: "HD"
    },
	{ 
        id: "P12", 
        titulo: "Gladiador", 
        poster: "https://www.themoviedb.org/t/p/w600_and_h900_face/p08mUnCktZ2opGihZTAn7OqzOoi.jpg", 
        bg: "https://image.tmdb.org/t/p/original/aZtwH3RQ0L8jbInxr7OSc9tlGMJ.jpg", 
        video: "https://www.burstcloud.co/embed/fb1e061ea09e62129c3b2b2af870731307df6803ec900c09ffeacb7d1038e6ac/gladiador1.mp4", 
        descripcion: "En el año 180, Marco Aurelio transfiere el poder a Máximo, pero su hijo Cómodo intenta asesinarlo.", 
        fecha: "2021", 
        tags: "Acción, Drama y Aventura",
        etiqueta: "",
        coincidencia: "82% para ti",
        calidad: "HD"
    },
	{ 
        id: "P13", 
        titulo: "Gladiador II", 
        poster: "https://www.themoviedb.org/t/p/w600_and_h900_face/fbcs5AxrdXwyj1b8bGGMgC9kXrM.jpg", 
        bg: "https://image.tmdb.org/t/p/original/qoZHK7EVaO70jaucJYEvI1tGqRh.jpg", 
        video: "https://www.burstcloud.co/embed/1ad069bc269eff33fcadf37e90cf75c53de4b1cc2bb90a4cc1a2c29c51d46a28/gladiador2.mp4", 
        descripcion: "Lucius, tras la muerte de Maximus y la caída de su hogar, debe luchar en el Coliseo para restaurar la gloria de Roma.", 
        fecha: "2024", 
        tags: "Acción, Drama y Aventura",
        etiqueta: "",
        coincidencia: "66% para ti",
        calidad: "HD"
    },
	{ 
        id: "P14", 
        titulo: "Duna ", 
        poster: "https://www.themoviedb.org/t/p/w600_and_h900_face/gDzOcq0pfeCeqMBwKIJlSmQpjkZ.jpg", 
        bg: "https://image.tmdb.org/t/p/original/h3HsfV8Kn9Sz2QWUYYdP5ya23hx.jpg", 
        video: "https://www.burstcloud.co/embed/2989e8a490b4c2735d692de5c3d125f9a0a3c90c381d256a5a220e674221de01/Dune1.mp4", 
        descripcion: "Paul Atreides, un joven brillante y talentoso nacido en un gran destino más allá de su entendimiento, debe viajar al planeta más peligroso del universo para asegurar el futuro de su familia y de su pueblo.", 
        fecha: "2021", 
        tags: "Ciencia ficción y Aventura",
        etiqueta: "",
        coincidencia: "78% para ti",
        calidad: "HD"
    },
	{ 
        id: "P15", 
        titulo: "Duna: Parte dos", 
        poster: "https://www.themoviedb.org/t/p/w600_and_h900_face/6o5cJjA4srfvU52UKWaqPUuPPgl.jpg", 
        bg: "https://image.tmdb.org/t/p/original/wauiyiVXpdvTvt2CzdSWbYlbaE3.jpg", 
        video: "https://www.burstcloud.co/embed/a8bf356a133f0790cd576eb8c8c7daa109966b9dd597af3b9709dcf812756808/dune2.mp4", 
        descripcion: "Paul Atreides se une a Chani y los Fremen en busca de venganza contra quienes destruyeron a su familia, enfrentando una decisión entre amor y destino universal.", 
        fecha: "2024", 
        tags: "Ciencia ficción y Aventura",
        etiqueta: "",
        coincidencia: "81% para ti",
        calidad: "HD"
    },
	{ 
        id: "P16", 
        titulo: "¿Qué Pasó Ayer?", 
        poster: "https://www.themoviedb.org/t/p/w600_and_h900_face/kZaaJQEi7n3mrBct1H3l2g45Ijb.jpg", 
        bg: "https://image.tmdb.org/t/p/original/iuRVt8tFiXDPGgzavhuSa3QHRxD.jpg", 
        video: "https://www.burstcloud.co/embed/b45a563c34b55e77bb156149dceceaf1f3e3ec360a2ad8cd74388e83e3cb3fb7/quepasoayer1.mp4", 
        descripcion: "El novio y tres amigos celebran una despedida de soltero en Las Vegas. Al despertar con resaca, descubren que el novio ha desaparecido, y hay un tigre y un bebé.", 
        fecha: "2009", 
        tags: "Comedia y Aventura",
        etiqueta: "",
        coincidencia: "73% para ti",
        calidad: "HD"
    },
	{ 
        id: "P17", 
        titulo: "¿Qué Pasó Ayer? Parte II", 
        poster: "https://www.themoviedb.org/t/p/w600_and_h900_face/dzaVnS19yDTkkGZRlf89sND75i7.jpg", 
        bg: "https://image.tmdb.org/t/p/original/kdKHiiUvGpcOjxPfyblxTuGHw8o.jpg", 
        video: "https://www.burstcloud.co/embed/0f1a58989c199817466106492373059e3bc164a83419af0aa4aeb872a8f88f89/quepasoayer2.mp4", 
        descripcion: "Alan, Stu y Phil despiertan en un hotel en Tailandia sin recordar nada, y deben encontrar a Teddy, el hermano de Lauren, antes de la boda de Stu.", 
        fecha: "2011", 
        tags: "Comedia y Aventura",
        etiqueta: "",
        coincidencia: "69% para ti",
        calidad: "HD"
    },
	{ 
        id: "P18", 
        titulo: "¿Qué Pasó Ayer? Parte III", 
        poster: "https://www.themoviedb.org/t/p/w600_and_h900_face/1goOfrB3ZRnoJenHHIDqiskMi9q.jpg", 
        bg: "https://image.tmdb.org/t/p/original/ll7iTzMsGsPK7tfPCoiD315sHmN.jpg", 
        video: "https://www.burstcloud.co/embed/15983ba8928f6cbcdc72e1be297d4d9284397ac52dbdb7037dbb9085935b59ac/quepasoayer3.mp4", 
        descripcion: "Alan, tras la muerte de su padre, es llevado al centro por Phil, Stu y Doug, sin boda ni fiesta, solo caos con Chow.", 
        fecha: "2013", 
        tags: "Comedia y Aventura",
        etiqueta: "",
        coincidencia: "71% para ti",
        calidad: "HD"
    },
	{ 
        id: "P19", 
        titulo: "Deadpool", 
        poster: "https://www.themoviedb.org/t/p/w600_and_h900_face/3E53WEZJqP6aM84D8CckXx4pIHw.jpg", 
        bg: "https://image.tmdb.org/t/p/original/k2VX0gFu2BEJhvduQTq2ioYp8z7.jpg", 
        video: "https://www.burstcloud.co/embed/73a7309cc9edd69f7b740355bbd81c7aabb9545e8145aa6461031677e3ceb884/Deappool1.mp4", 
        descripcion: "Deadpool narra el origen de Wade Wilson, un ex-operativo que, tras un experimento cruel, obtiene poderes de curación y se convierte en mercenario, buscando venganza con humor retorcido.", 
        fecha: "2016", 
        tags: "Acción, Aventura y Comedia",
        etiqueta: "",
        coincidencia: "73% para ti",
        calidad: "HD"
    },
	{ 
        id: "P20", 
        titulo: "Deadpool 2", 
        poster: "https://www.themoviedb.org/t/p/w600_and_h900_face/fgPTa4IS07Pygz0Q1WJnRgOP7r7.jpg", 
        bg: "https://image.tmdb.org/t/p/original/ngoXNWBeJABz6i1SyNDj0d3GD6P.jpg", 
        video: "https://www.burstcloud.co/embed/7c4616920f3c49ae1fb7aecd8576ca97da21b899556ee21234beb30651973cce/deadpool2.mp4", 
        descripcion: "El mercenario mutante malhablado Wade Wilson (alias Deadpool), reúne a un equipo de mutantes para proteger a un joven con habilidades sobrenaturales del brutal cyborg Cable, que viaja a través del tiempo.", 
        fecha: "2018", 
        tags: "Acción, Aventura y Comedia",
        etiqueta: "",
        coincidencia: "75% para ti",
        calidad: "HD"
    },
	{ 
        id: "P21", 
        titulo: "Deadpool & Wolverine", 
        poster: "https://www.themoviedb.org/t/p/w600_and_h900_face/6aY3OzCIdxoBMYdiH5s17rWFFFA.jpg", 
        bg: "https://image.tmdb.org/t/p/original/rLLA3CehQydC9RsSwIaA54gXNPp.jpg", 
        video: "https://www.burstcloud.co/embed/2ddcb5bd4f1b280c50ece46f466d0bb5fef2d0dae2082c74c0a1f9b21ff7c9d2/deadpoolvswolverine.mp4", 
        descripcion: "Wade Wilson, apático en la vida civil, regresa como Deadpool para enfrentar una amenaza, junto al reacio Wolverine.", 
        fecha: "2024", 
        tags: "Acción, Aventura y Comedia",
        etiqueta: "",
        coincidencia: "76% para ti",
        calidad: "HD"
    },
	{ 
        id: "P22", 
        titulo: "Beetlejuice Beetlejuice", 
        poster: "https://www.themoviedb.org/t/p/w600_and_h900_face/9w6YSml4bDADocgEVTpMUy1MBd1.jpg", 
        bg: "https://image.tmdb.org/t/p/original/8tRGvXpVfPHkGqYSGcoeWsAT9o8.jpg", 
        video: "https://www.burstcloud.co/embed/0e0301f079893809743e3a848cab99d8d8c4fdb068458815a633beee00070d4b/Beetlejuice%20Beetlejuice.mp4", 
        descripcion: "Tras una tragedia, la familia Deetz regresa a Winter River, donde Lydia y su hija Astrid provocan un caos sobrenatural.", 
        fecha: "2024", 
        tags: "Comedia, Fantasía y Terror",
        etiqueta: "",
        coincidencia: "69% para ti",
        calidad: "HD"
    },
	{ 
        id: "P23", 
        titulo: "Batman inicia", 
        poster: "https://www.themoviedb.org/t/p/w600_and_h900_face/zBVNawbcB9z3cQw3uOvQ6dTLBS2.jpg", 
        bg: "https://image.tmdb.org/t/p/original/3MEXbwZUTzzAYXZTsHiWNMSmAVW.jpg", 
        video: "https://www.burstcloud.co/embed/9bb1c2716bf9a0f6f6e3597e6bbd34d41f59fd23b54e070517543f242d9bdcc6/batmanbegins.mp4", 
        descripcion: "Después de entrenar con su mentor, Batman comienza su lucha para liberar a Ciudad Gótica de la corrupción.", 
        fecha: "2005", 
        tags: "Drama, Crimen y Acción",
        etiqueta: "",
        coincidencia: "85% para ti",
        calidad: "HD"
    },
	{ 
        id: "P24", 
        titulo: "Batman: El caballero de la noche", 
        poster: "https://www.themoviedb.org/t/p/w600_and_h900_face/vLFCrzI3V4kbze877tP1H7TqppL.jpg", 
        bg: "https://image.tmdb.org/t/p/original/adlPZoRdysBMVTSTsGamcn5apYt.jpg", 
        video: "https://www.burstcloud.co/embed/53e422d8c02951ba377dfd008910dc7c7d0238be428440b1b9e58ecc3f2f81c0/thedartknigth.mp4", 
        descripcion: "Batman enfrenta una dura prueba psicológica y física ante el caos causado por el Joker en Gotham.", 
        fecha: "2008", 
        tags: "Drama, Crimen y Acción",
        etiqueta: "",
        coincidencia: "89% para ti",
        calidad: "HD"
    },
	{ 
        id: "P25", 
        titulo: "Batman: El caballero de la noche asciende", 
        poster: "https://www.themoviedb.org/t/p/w600_and_h900_face/pi6mwFCtTDIAHOHWan4AQ36Tdh2.jpg", 
        bg: "https://image.tmdb.org/t/p/original/8p1btPA5ME6OsfAmL3bcf7P2yoP.jpg", 
        video: "https://www.burstcloud.co/embed/0ee02ce488a61af2495f3a1f125ad4de90fadf4a66bd0bc62615d43a66b75199/thedarknithgrises.mp4", 
        descripcion: "Ocho años después del reinado de anarquía del Joker, Batman, con la ayuda de la enigmática Gatúbela, se ve obligado a salir de su exilio para salvar a Ciudad Gótica del brutal terrorista guerrillero Bane.", 
        fecha: "2012", 
        tags: "Drama, Crimen y Acción",
        etiqueta: "",
        coincidencia: "78% para ti",
        calidad: "HD"
    },
	{ 
        id: "P26", 
        titulo: "Venom", 
        poster: "https://www.themoviedb.org/t/p/w600_and_h900_face/jMBTJQiHAyGlZR05J2sq5coA6ew.jpg", 
        bg: "https://image.tmdb.org/t/p/original/fZL447eRii2HiWBk7QzOIFZoWJd.jpg", 
        video: "https://www.burstcloud.co/embed/32b76d38a33be6eaf190d86052a0d95af75502e10b787a4ca19444912ab52b67/venon%202.mp4", 
        descripcion: "Eddie Brock, tras un escándalo, se convierte en el anfitrión del violento simbionte alienígena Venom.", 
        fecha: "2018", 
        tags: "Ciencia ficción y Acción",
        etiqueta: "",
        coincidencia: "62% para ti",
        calidad: "HD"
    },
	{ 
        id: "P27", 
        titulo: "Venom: Carnage Liberado", 
        poster: "https://www.themoviedb.org/t/p/w600_and_h900_face/8oe2CxKi8AlzccgX6RD4hB5xGQx.jpg", 
        bg: "https://image.tmdb.org/t/p/original/eENEf62tMXbhyVvdcXlnQz2wcuT.jpg", 
        video: "https://www.burstcloud.co/embed/32b76d38a33be6eaf190d86052a0d95af75502e10b787a4ca19444912ab52b67/venon%202.mp4", 
        descripcion: "Eddie Brock y su simbionte Venom todavía están intentando descubrir cómo vivir juntos cuando un preso que está en el corredor de la muerte se infecta con un simbionte propio.", 
        fecha: "2021", 
        tags: "Ciencia ficción y Acción",
        etiqueta: "",
        coincidencia: "71% para ti",
        calidad: "HD"
    },
	{ 
        id: "P28", 
        titulo: "Venom: El último baile", 
        poster: "https://www.themoviedb.org/t/p/w600_and_h900_face/8oe2CxKi8AlzccgX6RD4hB5xGQx.jpg", 
        bg: "https://image.tmdb.org/t/p/original/eENEf62tMXbhyVvdcXlnQz2wcuT.jpg", 
        video: "https://www.burstcloud.co/embed/2b48b56c4790d34a6b95a847c2437392ef2c4ce928ffef85f19c311550e33d85/venon3.mp4", 
        descripcion: "Eddie Brock, tras un escándalo, se convierte en el anfitrión del violento simbionte alienígena Venom.", 
        fecha: "2024", 
        tags: "Ciencia ficción y Acción",
        etiqueta: "",
        coincidencia: "77% para ti",
        calidad: "HD"
    },
	{ 
        id: "P29", 
        titulo: "Kung Fu Panda", 
        poster: "https://www.themoviedb.org/t/p/w600_and_h900_face/8oe2CxKi8AlzccgX6RD4hB5xGQx.jpg", 
        bg: "https://image.tmdb.org/t/p/original/eENEf62tMXbhyVvdcXlnQz2wcuT.jpg", 
        video: "https://www.burstcloud.co/embed/4cff37b0d0dda7447e98e3639b288da540981df40da2efab9b43386d79bd415a/kunfupanda1.mp4", 
        descripcion: "Po, el panda perezoso, se entrena con ayuda de Shifu y los Cinco Furiosos para ser héroe.", 
        fecha: "2008", 
        tags: "Animación, Familia, Comedia y Acción",
        etiqueta: "",
        coincidencia: "73% para ti",
        calidad: "HD"
    },
	{ 
        id: "P30", 
        titulo: "Kung Fu Panda 2", 
        poster: "https://www.themoviedb.org/t/p/w600_and_h900_face/aNji9U9SPTecmoqGippQUBEyouy.jpg", 
        bg: "https://image.tmdb.org/t/p/original/w9IXDBPkdoLm9tETYYJS2JUr9dJ.jpg", 
        video: "https://www.burstcloud.co/embed/d4ddf50aa34e86abefc3660ad2fcc8af1c779318fa3c1cec5ae2e81e8d1625d0/kunfupanda2.mp4", 
        descripcion: "Po, como Guerrero del Dragón, protege el Valle de la Paz junto a sus amigos. Un villano amenaza su vida y debe descubrir su origen para vencer.", 
        fecha: "2011", 
        tags: "Animación, Familia y Comedia",
        etiqueta: "",
        coincidencia: "71% para ti",
        calidad: "HD"
    },
	{ 
        id: "P31", 
        titulo: "Kung Fu Panda 3", 
        poster: "https://www.themoviedb.org/t/p/w600_and_h900_face/t11f8palNbICK9Ip5QLrUfhLJYq.jpg", 
        bg: "https://image.tmdb.org/t/p/original/tfEvP0Pnkj2AOpwLoexap6u7fWW.jpg", 
        video: "https://www.burstcloud.co/embed/a968f9511c6431deba00fe3de9c372144e836046057e0046bf3002b77063c7aa/kungfupanda3.mp4", 
        descripcion: "Mientras visita una aldea secreta de pandas con su padre, Po se ve obligado a improvisar un peculiar ejército para detener a un espíritu malvado que amenaza a toda China", 
        fecha: "2016", 
        tags: "Acción, Aventura, Comedia y Familia",
        etiqueta: "",
        coincidencia: "69% para ti",
        calidad: "HD"
    },
	{ 
        id: "P32", 
        titulo: "Kung Fu Panda 4", 
        poster: "https://www.themoviedb.org/t/p/w600_and_h900_face/7JspmokDnpm8SEg28wtstfGps0K.jpg", 
        bg: "https://image.tmdb.org/t/p/original/vdPjV35lrFVg2Itqn4FXONqhyn3.jpg", 
        video: "https://www.burstcloud.co/embed/f9b31b7b3e15225e8d848b445f28c41869654b1462cd3eb907b8242448a86808/kunfupanda4.mp4", 
        descripcion: "Po entrena un nuevo guerrero kung fu mientras enfrenta al villano Camaleón que revive enemigos pasados.", 
        fecha: "2024", 
        tags: "Comedia, Aventura y Fantasía",
        etiqueta: "",
        coincidencia: "70% para ti",
        calidad: "HD"
    },
	{ 
        id: "P33", 
        titulo: "Click: Perdiendo el Control", 
        poster: "https://www.themoviedb.org/t/p/w600_and_h900_face/fJADdrBkRB6QOhnSIPWCdmnLdLK.jpg", 
        bg: "https://image.tmdb.org/t/p/original/iX7Gc2eidasIIZLnX4tLMSKUVUS.jpg", 
        video: "https://www.burstcloud.co/embed/ad55f016c1a812d0ac85faf1ed7027cb6eb509ee97aceaea66fc6d88a6eacc41/click.mp4", 
        descripcion: "Michael compra un mando a distancia, controla su vida y se vuelve adicto a su poder.", 
        fecha: "2006", 
        tags: "Comedia, Drama y Fantasía",
        etiqueta: "",
        coincidencia: "69% para ti",
        calidad: "HD"
    },
	{ 
        id: "P34", 
        titulo: "Diario de una pasión", 
        poster: "https://www.themoviedb.org/t/p/w600_and_h900_face/kdJNpBcLJH0nDis8cjQHGjaAbRl.jpg", 
        bg: "https://image.tmdb.org/t/p/original/zdXnJqBaGFVtLoPNuMeKfEYUViZ.jpg", 
        video: "https://www.burstcloud.co/embed/1d083354d1380657501cfe17bc3b7248b5ee91cb774f60525cdd378e6622f911/diario%20de%20una%20pasion.mp4", 
        descripcion: "Un anciano lee a una mujer sobre la historia de amor de Noah y Allie, quienes vivieron un verano inolvidable antes de ser separados.", 
        fecha: "2021", 
        tags: "Romance y Drama",
        etiqueta: "",
        coincidencia: "79% para ti",
        calidad: "HD"
    },
	{ 
        id: "P35", 
        titulo: "Salvando al Soldado Ryan", 
        poster: "https://www.themoviedb.org/t/p/w600_and_h900_face/aMij3XE0wSoLHWqP7qK0fPOReTb.jpg", 
        bg: "https://image.tmdb.org/t/p/original/a3dmI6TtJ00zgOIPVgaJrouVFg8.jpg", 
        video: "https://www.burstcloud.co/embed/a652c7911d0a504eacf95e7d290eb4f60500fd5f81a67cf211e11fdb973079b1/salvando%20al%20soldado%20ryan.mp4", 
        descripcion: "En 1944, tras el desembarco en Normandía, un grupo de soldados americanos busca salvar al soldado James Ryan, cuyos hermanos han muerto en combate.", 
        fecha: "2021", 
        tags: "Bélica, Drama y Historia",
        etiqueta: "",
        coincidencia: "82% para ti",
        calidad: "HD"
    },
	{ 
        id: "P36", 
        titulo: "Milagros Inesperados", 
        poster: "https://www.themoviedb.org/t/p/w600_and_h900_face/7ezlnHDn6clFku58TmFmpKUQUqf.jpg", 
        bg: "https://image.tmdb.org/t/p/original/vxJ08SvwomfKbpboCWynC3uqUg4.jpg", 
        video: "https://www.burstcloud.co/embed/28b316bf397711beafed9331d06eb40a6e74b067138aa7711fe4595af3c3d6e1/milagros%20inesperados.mp4", 
        descripcion: "Las vidas de los guardias del corredor de la muerte se ven afectadas por uno de sus cargos: un hombre negro acusado de asesinato y violación de niños, pero que tiene un misterioso don.", 
        fecha: "1999", 
        tags: "Fantasía, Drama y Crimen",
        etiqueta: "",
        coincidencia: "89% para ti",
        calidad: "HD"
    },
	{ 
        id: "P37", 
        titulo: "Amenaza en el aire", 
        poster: "https://www.themoviedb.org/t/p/w600_and_h900_face/8T6nkYb4W8BIeafmFffyfsRciTL.jpg", 
        bg: "https://image.tmdb.org/t/p/original/pUitHTfEWwSSX1oKZl46aBfdfXY.jpg", 
        video: "https://www.burstcloud.co/embed/28b316bf397711beafed9331d06eb40a6e74b067138aa7711fe4595af3c3d6e1/milagros%20inesperados.mp4", 
        descripcion: "Un piloto lleva a un alguacil y a un fugitivo a juicio en Alaska, donde la tensión y la desconfianza crecen.", 
        fecha: "2025", 
        tags: "Acción y Suspense",
        etiqueta: "",
        coincidencia: "65% para ti",
        calidad: "HD"
    },
	{ 
        id: "P38", 
        titulo: "Mad Max: Furia en el camino ", 
        poster: "https://www.themoviedb.org/t/p/w600_and_h900_face/xJfbWr0mi9B2uKhnayBMFYgYDcJ.jpg", 
        bg: "https://image.tmdb.org/t/p/original/rGrSKPXJvD5j9YENIlvkj4kMU6h.jpg", 
        video: "https://www.burstcloud.co/embed/b1f2e02c6ed137c56f931b1f1b96660925853504e2f0b10e9ef93d302b587646/madmax.mp4", 
        descripcion: "Mad Max, huyendo de su pasado, se une a Furiosa y un grupo de rebeldes que escapan de Immortan Joe en una intensa persecución por el desierto en un War Rig.", 
        fecha: "2015", 
        tags: "Acción, Aventura y Ciencia ficción",
        etiqueta: "",
        coincidencia: "78% para ti",
        calidad: "HD"
    },
	{ 
        id: "P39", 
        titulo: "Furiosa: De la saga Mad Max", 
        poster: "https://www.themoviedb.org/t/p/w600_and_h900_face/tGHUlykWn9V2IIQ4ZaATIAq9VLB.jpg", 
        bg: "https://image.tmdb.org/t/p/original/dAeThs4mFr9QTtyMEibRGkERscj.jpg", 
        video: "https://www.burstcloud.co/embed/444d9276deef4e058d8c2539724a1ac8645a29a26ae534497ae97fd7e01b1051/furiosa.mp4", 
        descripcion: "Furiosa es secuestrada por moteros, enfrenta desafíos en un mundo en ruinas y lucha por regresar a casa.", 
        fecha: "2024", 
        tags: "Acción, Ciencia ficción y Aventura",
        etiqueta: "",
        coincidencia: "75% para ti",
        calidad: "HD"
    },
	{ 
        id: "P40", 
        titulo: "Cadena de Favores", 
        poster: "https://www.themoviedb.org/t/p/w600_and_h900_face/8MFVGTbYnOqAmwq6tLz8NUE5bZC.jpg", 
        bg: "https://image.tmdb.org/t/p/original/5GAbRBhBjQPsTXlagD3lTPBH3vz.jpg", 
        video: "https://www.burstcloud.co/embed/23b4af3f91d2c396970ef8ed7ad4cb1fe66a1da0cf86aedcc1b91893eb86a087/cadenadefavores.mp4", 
        descripcion: "Un niño crea un sistema de favores desinteresados, causando furor en la comunidad. Comedia entretenida.", 
        fecha: "2001", 
        tags: "Drama",
        etiqueta: "",
        coincidencia: "74% para ti",
        calidad: "HD"
    },
	{ 
        id: "P41", 
        titulo: "Harry Potter y la piedra filosofal", 
        poster: "https://www.themoviedb.org/t/p/w600_and_h900_face/3MKK7vAJLtSkBTABMTjxf6TOCo3.jpg", 
        bg: "https://image.tmdb.org/t/p/original/hziiv14OpD73u9gAak4XDDfBKa2.jpg", 
        video: "https://www.burstcloud.co/embed/23b4af3f91d2c396970ef8ed7ad4cb1fe66a1da0cf86aedcc1b91893eb86a087/cadenadefavores.mp4", 
        descripcion: "Harry Potter descubre en su cumpleaños que es un mago y entra a Hogwarts, donde aprende magia y su verdadera historia.", 
        fecha: "2001", 
        tags: "Drama, Adventura, Ciencia Ficcion",
        etiqueta: "",
        coincidencia: "7.9/10",
        calidad: "HD"
    },
	{ 
        id: "P42", 
        titulo: "Harry Potter y la cámara secreta", 
        poster: "https://www.themoviedb.org/t/p/w600_and_h900_face/d7lK3K1QWmcgjHyRMBV3rT2yzTM.jpg", 
        bg: "https://image.tmdb.org/t/p/original/pWkpvgDbyc7Cxe4aHEOkPx8oCtB.jpg", 
        video: "https://www.burstcloud.co/embed/e9a53eb3df80ada1960fbc9553e3acc6cb3e1f2143a1296f63fdb4a9daed5644/Harry%20Potter%20Y%20La%20C%C3%83%C2%A1mara%20Secreta.mp4", 
        descripcion: "Harry Potter recibe la visita de Dobby, un elfo doméstico, que le advierte sobre un peligro en Hogwarts. A pesar de esto, Ron y sus hermanos lo rescatan con un coche volador.", 
        fecha: "2002", 
        tags: "Drama, Adventura, Ciencia Ficcion",
        etiqueta: "",
        coincidencia: "7.7/10",
        calidad: "HD"
    },
	{ 
        id: "P43", 
        titulo: "Harry Potter y el prisionero de Azkaban", 
        poster: "https://www.themoviedb.org/t/p/w600_and_h900_face/xBph7rrwtxUuDxyZVDQtbP2H0sM.jpg", // 
        bg: "https://image.tmdb.org/t/p/original/zJbsaD7XqezmXi7tol7lX6HCAzT.jpg", 
        video: "https://www.burstcloud.co/embed/68c75b592f10c551106f6dd3f64e3a20bb99ac330280030b4a09e25120327e08/Harry%20Potter%20Y%20El%20Prisionero%20De%20Azkaban.mp4", 
        descripcion: "Harry Potter regresa a Hogwarts y descubre que Sirius Black, un fugitivo de Azkaban, lo está buscando.", 
        fecha: "2004", 
        tags: "Drama, Adventura, Ciencia Ficcion",
        etiqueta: "",
        coincidencia: "8.0/10",
        calidad: "HD"
    },
	{ 
        id: "P44", 
        titulo: "Harry Potter y el cáliz de fuego", 
        poster: "https://www.themoviedb.org/t/p/w600_and_h900_face/5hrrncgY7GfRHz6JmnhPlvJUONe.jpg", 
        bg: "https://image.tmdb.org/t/p/original/okPobv1v7AZECnKUCFCTZUw970u.jpg", 
        video: "https://www.burstcloud.co/embed/5ac9fb2d551069ce5df44fc9ed80c5ba9b42509066a383700cbb2a38d074cb88/Harry%20Potter%20Y%20El%20C%C3%83%C2%A1liz%20De%20Fuego.mp4", 
        descripcion: "Harry participa en el Torneo de los Tres Magos, enfrentando peligros mientras Voldemort regresa al poder.", 
        fecha: "2005", 
        tags: "Drama, Adventura, Ciencia Ficcion",
        etiqueta: "",
        coincidencia: "7.8/10",
        calidad: "HD"
    },
	{ 
        id: "P45", 
        titulo: "Harry Potter y la orden del Fénix", 
        poster: "https://www.themoviedb.org/t/p/w600_and_h900_face/xxXiM2Ij7plbzibKWW9BfDk23aI.jpg", 
        bg: "https://image.tmdb.org/t/p/original/rCniHYrpaLXcEOCiESwvPySp2GX.jpg", 
        video: "https://www.burstcloud.co/embed/b8f1b5e3b102556dec787acaee8ab8577b46a310b82a8c51b8d5373ca3e2962b/Harry%20Potter%20Y%20La%20Orden%20Del.mp4", 
        descripcion: "Harry enfrenta la negación del regreso de Voldemort por parte del Ministerio de Magia y la tiranía de Umbridge en Hogwarts.", 
        fecha: "2007", 
        tags: "Drama, Adventura, Ciencia Ficcion",
        etiqueta: "",
        coincidencia: "7.7/10",
        calidad: "HD"
    },
	{ 
        id: "P46", 
        titulo: "Harry Potter y el misterio del príncipe", 
        poster: "https://www.themoviedb.org/t/p/w600_and_h900_face/tO0UGkNuQoxyXve0mvwtXP49NAO.jpg", 
        bg: "https://image.tmdb.org/t/p/original/gcusUxQrzi6txonROEeHyCuXnKd.jpg", 
        video: "https://www.burstcloud.co/embed/d079b482b6fe9c251734ee8fa87914a903dac9150a241796196aad77bfabcd85/Harry%20Potter%20Y%20El%20Misterio%20Del%20Pr%C3%83%C2%ADncipe.mp4", 
        descripcion: "Harry descubre secretos de Voldemort con Dumbledore mientras un viejo libro de pociones le ayuda en su sexto año en Hogwarts.", 
        fecha: "2009", 
        tags: "Drama, Adventura, Ciencia Ficcion",
        etiqueta: "",
        coincidencia: "7.7/10",
        calidad: "HD"
    },
	{ 
        id: "P47", 
        titulo: "Harry Potter y las reliquias de la muerte (1ª parte).", 
        poster: "https://www.themoviedb.org/t/p/w600_and_h900_face/bZYziROYpqXI1DeW4Xz3egMOqej.jpg", 
        bg: "https://image.tmdb.org/t/p/original/vptTQxOH4eeBzSpT0ceeQWUCwuN.jpg", 
        video: "https://www.burstcloud.co/embed/114d0fa906bc81297892ef028dbcc9c6fa40528ef1bdd3470405558005b55830/Harry%20Potter%207%20Y%20Las%20Reliquias%20De%20La%20Muerte%20%C3%A2%C2%80%C2%93%20Parte%20I.mp4", 
        descripcion: "Harry, Hermione y Ron buscan los últimos horrocruxes para derrotar a Voldemort mientras huyen y enfrentan crecientes peligros.", 
        fecha: "2010", 
        tags: "Drama, Adventura, Ciencia Ficcion",
        etiqueta: "",
        coincidencia: "7.7/10",
        calidad: "HD"
    },
	{ 
        id: "P48", 
        titulo: "Harry Potter y las reliquias de la muerte (2ª parte).", 
        poster: "https://www.themoviedb.org/t/p/w600_and_h900_face/aM1TuUiPtV8OAZyu61CTdy9Ymtk.jpg", 
        bg: "https://image.tmdb.org/t/p/original/ngqeWyeGsMR8gEGq9qKpTZXk0Pk.jpg", 
        video: "https://www.burstcloud.co/embed/bd0ef44edc61e68a411ccfb36d523a0645af0f92eecd2b0cf42dbe40d7a2b0ee/Harry%20Potter%207%20Y%20Las%20Reliquias%20De%20La%20Muerte%20%C3%A2%C2%80%C2%93%20Parte%202.mp4", 
        descripcion: "Harry y sus amigos buscan los últimos horrocruxes mientras Voldemort toma Hogwarts. La batalla final decidirá el destino del mundo mágico.", 
        fecha: "2011", 
        tags: "Drama, Adventura, Ciencia Ficcion",
        etiqueta: "",
        coincidencia: "8.1/10",
        calidad: "HD"
    },
	{ 
        id: "P49", 
        titulo: "Flow.", 
        poster: "https://www.themoviedb.org/t/p/w600_and_h900_face/sx81sF46pooqfqbbqFy84xXpXpH.jpg", 
        bg: "https://image.tmdb.org/t/p/original/2HFXAuFRn444kJ9MgloJ0COjcpO.jpg", 
        video: "https://www.burstcloud.co/embed/019dabcf88a9e2c260f7d3543c5a57cbc4ca2a32b9366103fe47ed9d9a4f02c0/Flow.mp4", 
        descripcion: "Un gato solitario, tras perder su hogar por una inundación, se refugia en un barco con otras especies. Juntos, deben superar diferencias y desafíos en un mundo sumergido.", 
        fecha: "2024", 
        tags: "Animacion, Aventura, Fantasia",
        etiqueta: "",
        coincidencia: "8.3/10",
        calidad: "HD"
    },
	{ 
        id: "P50", 
        titulo: "Rápidos y furiosos X", 
        poster: "https://www.themoviedb.org/t/p/w600_and_h900_face/x3zlm6VxPvVrYWE3bHkYUQMR798.jpg", 
        bg: "https://image.tmdb.org/t/p/original/4XM8DUTQb3lhLemJC51Jx4a2EuA.jpg", 
        video: "https://www.burstcloud.co/embed/d3138f41a11f307024302f7ea1291c10cff6ff1687178270e935bc4d5f746eb7/RapidosYfurisos10.mp4", 
        descripcion: "Dom Toretto y su familia enfrentan a su enemigo más letal: una amenaza del pasado que busca venganza y está decidido a destruir todo lo que Dom ama.", 
        fecha: "2023", 
        tags: "Accion, Crimen, Suspense",
        etiqueta: "",
        coincidencia: "7.1/10",
        calidad: "HD"
    },
	{ 
        id: "P51", 
        titulo: "Frankenhooker", 
        poster: "https://www.themoviedb.org/t/p/w600_and_h900_face/juIdU7u6stz7NasKJEnDoqWMssw.jpg", 
        bg: "https://image.tmdb.org/t/p/original/9tS0TWnZ3gTzhWL4XgadQ2BvTYW.jpg", 
        video: "https://www.burstcloud.co/embed/b313a252ccf29b9b7503db931bbf40832331365b44e4b15bad5b240af40211b2/FrankePuta.mp4", 
        descripcion: "Jeffrey, un electricista aficionado a la bioquímica, pierde a su novia en un accidente y decide reconstruir su cuerpo con partes de prostitutas para revivirla.", 
        fecha: "1990", 
        tags: "Comedia, Terror, Ficcion",
        etiqueta: "",
        coincidencia: "6.2/10",
        calidad: "HD"
    },
	{ 
        id: "P52", 
        titulo: "Predestinación", 
        poster: "https://www.themoviedb.org/t/p/w600_and_h900_face/qXabr1nGFE3HCdIlU9xFGqALALg.jpg", 
        bg: "https://image.tmdb.org/t/p/original/iNHYPrmH3nq1W2mpcG9SOeMAr8J.jpg", 
        video: "https://www.burstcloud.co/embed/9d7ab343a8e9a4a4e02f00665799dec96fc617af41937cfd692d018675475b5f/predestinacion.mp4", 
        descripcion: "Un agente temporal debe detener a un terrorista mientras trabaja encubierto en los años 70. Allí, conoce a alguien con una historia inesperada.", 
        fecha: "2014", 
        tags: "Drama, Fantasia, Ficcion",
        etiqueta: "",
        coincidencia: "8.6/10",
        calidad: "HD"
    },
	{ 
        id: "P53", 
        titulo: "La Guerra de los Mundos", 
        poster: "https://www.themoviedb.org/t/p/w600_and_h900_face/voW0ysgAalYWqm2SsBzSfkNNN1K.jpg", 
        bg: "https://image.tmdb.org/t/p/original/pp3f9aEWjgsdP0uY2Al7yEhmRN8.jpg", 
        video: "https://www.burstcloud.co/embed/d4d34badb702711770e65b5299d99539cc0b805d3e35a71f727c395aed051f96/laguerradelosmunods.mp4", 
        descripcion: "Mientras la Tierra es invadida por máquinas alienígenas de combate, una familia lucha por la supervivencia.", 
        fecha: "2005", 
        tags: "Aventura, Suspenso, Ciencia Ficcion",
        etiqueta: "ESTRENO",
        coincidencia: "6.9/10",
        calidad: "HD"
    },
	{ 
        id: "P54", 
        titulo: "Sherlock Holmes", 
        poster: "https://www.themoviedb.org/t/p/w600_and_h900_face/gf4eNEw79XVbKYDBEQKgWPezQNY.jpg", 
        bg: "https://image.tmdb.org/t/p/original/veXdzn7LL0bFIDGmE7tTkvRg0qV.jpg", 
        video: "https://www.burstcloud.co/embed/d03ca0e6dc457c8f3ada3d8246f802635b600f8a5f91fe7a1cd7a81d1af84a17/serlonholmes1.mp4", 
        descripcion: "Holmes enfrenta a un enemigo formidable mientras desentraña un complot que amenaza con destruir el país.", 
        fecha: "2009", 
        tags: "Aventura, Accion, Crimen",
        etiqueta: "ESTRENO",
        coincidencia: "7.2/10",
        calidad: "HD"
    },
	{ 
        id: "P55", 
        titulo: "Sherlock Holmes: Juego de sombras", 
        poster: "https://www.themoviedb.org/t/p/w600_and_h900_face/cDu2Ti4uwF1yq6jgjsybe7UzZDI.jpg", 
        bg: "https://image.tmdb.org/t/p/original/nVMalJRUsOeGP5xPx9ULmirZ4cJ.jpg", 
        video: "https://www.burstcloud.co/embed/fb8b80c4489e1d19ad622a7c1a7e292aeed85c25510ddefcfc4feb1e93cb25e0/sherloholmes2.mp4", 
        descripcion: "El detective Sherlock Holmes está tras la pista del profesor Moriarty, que está llevando a cabo una serie de crímenes al azar en toda Europa.", 
        fecha: "2011", 
        tags: "Aventura, Accion, Crimen",
        etiqueta: "ESTRENO",
        coincidencia: "7.1/10",
        calidad: "HD"
    },
	{ 
        id: "P56", 
        titulo: "Observados", 
        poster: "https://www.themoviedb.org/t/p/w600_and_h900_face/rdspkGeXrprR2GxQqlRSHCJl617.jpg", 
        bg: "https://image.tmdb.org/t/p/original/oZDRuGHhe5uY8wBqFJcJZT9kdvJ.jpg", 
        video: "https://www.burstcloud.co/embed/7eaec03166e912c1850d279aa92d35596e92231a45106aff4a3c5f04abe534dc/observados.mp4", 
        descripcion: "Mina, una artista de 28 años, queda atrapada en un bosque irlandés con tres desconocidos, mientras misteriosas criaturas los acechan cada noche.", 
        fecha: "2024", 
        tags: "Fantasia, Terror, Misterio",
        etiqueta: "ESTRENO",
        coincidencia: "6.4/10",
        calidad: "HD"
    },
	{ 
        id: "P57", 
        titulo: "Tropa de Élite", 
        poster: "https://www.themoviedb.org/t/p/w600_and_h900_face/uNmhgNiUzZAknt4sjY1id8nbFCG.jpg", 
        bg: "https://image.tmdb.org/t/p/original/b8o8Lp0vg3HBiYPOxBPHc05y9Ev.jpg", 
        video: "https://www.burstcloud.co/embed/e67e7bf767000763806c0ded7a9b0015476fa2ecea02479ac65bddc6c23a62ef/tropaelite1.mp4", 
        descripcion: "En 1997, el capitán Nascimento lidera el BOPE en Río de Janeiro. Antes de retirarse, entrena a dos policías para enfrentar el crimen en las favelas.", 
        fecha: "2007", 
        tags: "Drama, Accion, Crimen",
        etiqueta: "ESTRENO",
        coincidencia: "8.0/10",
        calidad: "HD"
    },
	{ 
        id: "P58", 
        titulo: "Tropa de Élite 2", 
        poster: "https://www.themoviedb.org/t/p/w600_and_h900_face/geK5X7cIWap06q7J2ZiyQr2scrc.jpg", 
        bg: "https://image.tmdb.org/t/p/original/nFLP0AL8bGQncX7UCbvUQMVsS8J.jpg", 
        video: "https://www.burstcloud.co/embed/32c28fcd432212c6124fd0bd3ed8fa3f2c976fb46610ac4c2914eab9c82f8d0f/tropaelite1.mp4", 
        descripcion: "Nascimento, ahora un alto oficial de seguridad en Río de Janeiro, se enfrenta a la corrupción política y a las milicias paramilitares que controlan las favelas.", 
        fecha: "2010", 
        tags: "Drama, Accion, Crimen",
        etiqueta: "ESTRENO",
        coincidencia: "7.8/10",
        calidad: "HD"
    },
	
];